{% set name = "passlib" %}
{% set version = "1.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: defd50f72b65c5402ab2c573830a6978e5f202ad0d984793c8dde2c4152ebe04
  patches:
    # https://foss.heptapod.net/python-libs/passlib/-/issues/196
    - patches/0001-bcrypt5-compatibility.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    # Needed for pkg_resources in Python 3.12+
    - setuptools  # [py>311]
    - argon2-cffi >=18.2.0
    - bcrypt >=3.1.0
    - cryptography

test:
  source_files:
    - passlib/tests
  requires:
    - pip
    - pytest
  imports:
    - passlib
    - passlib.crypto
    - passlib.ext
    - passlib.handlers
    - passlib.utils
  commands:
    - pip check
    # test_dummy_verify passes locally but fails on CI with: AssertionError: 0.08806849992834032 != 0.05 within 0.010000000000000002 delta (0.03806849992834031 difference)
    - python -m pytest passlib/tests -v --deselect passlib/tests/test_context.py::CryptContextTest::test_dummy_verify

about:
  home: https://foss.heptapod.net/python-libs/passlib
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: comprehensive password hashing framework supporting over 30 schemes
  description: |
    Passlib is a password hashing library for Python, which provides
    cross-platform implementations of over 30 password hashing algorithms, as
    well as a framework for managing existing password hashes. It's designed to
    be useful for a wide range of tasks, from verifying a hash found in
    /etc/shadow, to providing full-strength password hashing for multi-user
    applications.
  doc_url: https://passlib.readthedocs.io
  dev_url: https://foss.heptapod.net/python-libs/passlib

extra:
  recipe-maintainers:
    - pmlandwehr
