travis:
  secure:
    BINSTAR_TOKEN: Usd+NuK1DowLSQatk4uCflYmGnLzlzNvFbwyifPS1O5PI52PqpY8IFg0FpFrHUUvzWhrPLCv/OUqFxb5tHN6z7InFsiMsdCxWO/XY/D/sCs3rS6xLjOQyGk5cP5RNwrNoF9oOEWE4uibYpZm5yXnJYdKqJSl0rXNnHwLGnCyyfzEaYokfsMPYb8mgUS4xH4nT1HI8jwlZcY4OQYHYwtwko2v93uyBVg7pCKGXG0BhFU58XqRzNAVynfDU9B/m4fV8E1wqa58giB+R1XGtmzgR0/g1VvwrhNe07otmv0C/jCmj8LMN4A2mvtul6q+IZ0eiIgxuuFnX+MJo4kxsV3yTGf4KzolbNL2atVRs+oFzZeujdm7j+opm+Z+Jv06DdymGqm4AuUOITPxmnJ4x+EE54xTpNhSdh/xjuct7/XlsJ66fYcBCuaDmgu/7EvJNbTD77DjOGP2CbvW02GQI/dET6HmGdpXtMLKvy8M+VYXS9kkCJfiBSRX8U+aQbEAy0EsKmCiTRKl4xlY/6AozB6TG9T9MH3qK6wbLsxbMcUd+oXU7Cy7ZErn/RLKODxOFiJPxgPtUVc/gabJYARSOdFbDwjpUXb1T+GivcxDQlrWhmMIn+Gm4bOUyWEp7S9RTcgKY3AlT84/3pn+7c3ZgbarSWRxnzzet8ZeoOlvCNJ9sKQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
